/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import vistas.empleado.PrincipalEmpleado;
import vistas.admin.PrincipalAdmin;
import controladores.AdminControlador;
import controladores.EmpleadoControlador;
import jakarta.validation.ConstraintViolationException;
import java.sql.SQLException;
import java.util.Arrays;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author perso
 */
public class Login extends JFrame {
    private AdminControlador adminControlador;
    private EmpleadoControlador empleadoControlador;

    /**
     * Creates new form Login
     */
    public Login() {
        adminControlador = new AdminControlador();
        empleadoControlador = new EmpleadoControlador();
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblBienvenida = new javax.swing.JLabel();
        separado1 = new javax.swing.JSeparator();
        cbxRol = new javax.swing.JComboBox<>();
        lblRol = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtfEmail = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        pwdfPassword = new javax.swing.JPasswordField();
        separador2 = new javax.swing.JSeparator();
        btnIniciarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("INICIO DE SESIÓN");
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(600, 400));
        setResizable(false);

        header.setBackground(new java.awt.Color(0, 43, 91));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Sistema de Gestión de Expendio de Bebidas");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(lblTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblBienvenida.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblBienvenida.setForeground(new java.awt.Color(33, 33, 33));
        lblBienvenida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBienvenida.setText("Bienvenido(a) a la aplicación. Por favor, ingrese sus credenciales para continuar.");

        separado1.setForeground(new java.awt.Color(224, 224, 224));

        cbxRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Empleado", "Administrador" }));

        lblRol.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblRol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rol.png"))); // NOI18N
        lblRol.setText("Rol");

        lblEmail.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user.png"))); // NOI18N
        lblEmail.setText("Correo Electrónico");

        lblPassword.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/password.png"))); // NOI18N
        lblPassword.setText("Contraseña");

        separador2.setForeground(new java.awt.Color(224, 224, 224));

        btnIniciarSesion.setBackground(new java.awt.Color(0, 80, 157));
        btnIniciarSesion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnIniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciarSesion.setText("Iniciar Sesión");
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(separado1)
                    .addComponent(lblRol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblBienvenida, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
                    .addComponent(cbxRol, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtfEmail)
                    .addComponent(pwdfPassword)
                    .addComponent(lblPassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(separador2))
                .addGap(14, 14, 14))
            .addGroup(layout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addComponent(btnIniciarSesion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblBienvenida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separado1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRol)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pwdfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(separador2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIniciarSesion)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
        String email = txtfEmail.getText().trim();
        char[] passwordChars = pwdfPassword.getPassword();
        String password = new String(passwordChars);
        Arrays.fill(passwordChars, '\0');
        
        if (email.isEmpty() || password.isEmpty()) {
            mostrarDialogo("Por favor complete todos los campos",
                    "CAMPOS VACÍOS",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (cbxRol.getSelectedItem().equals("Empleado")) {
            autenticarEmpleado(email, password);
        } else if (cbxRol.getSelectedItem().equals("Administrador")) {
            autenticarAdmin(email, password);
        }
    }//GEN-LAST:event_btnIniciarSesionActionPerformed
    
    private void autenticarAdmin(String email, String password) {
        try {
            adminControlador.autenticarAdmin(email, password);
            mostrarDialogo("Login exitoso. Bienvenido(a) al sistema.",
                    "ÉXITO",
                    JOptionPane.INFORMATION_MESSAGE);
            PrincipalAdmin principalAdmin = new PrincipalAdmin();
            principalAdmin.setVisible(true);
            this.dispose();
        } catch (ConstraintViolationException e) {
            mostrarErrorValidaciones(e);
        } catch (IllegalArgumentException e) {
            mostrarDialogo(e.getMessage(),
                    "ERROR DE AUTENTICACIÓN",
                    JOptionPane.ERROR_MESSAGE);
        } catch (SQLException e) {
            mostrarDialogo(e.getMessage(),
                    "ERROR DE CONEXIÓN",
                    JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            mostrarDialogo("Error inesperado: " + e.getMessage(),
                    "ERROR",
                    JOptionPane.ERROR_MESSAGE);
        } finally {
            pwdfPassword.setText("");
            txtfEmail.requestFocus();
        }
    }
    
    private void autenticarEmpleado(String email, String password) {
        try {
            empleadoControlador.autenticarEmpleado(email, password);
            mostrarDialogo("Login exitoso. Bienvenido(a) al sistema.", 
                    "ÉXITO",
                    JOptionPane.INFORMATION_MESSAGE);
            PrincipalEmpleado principalEmpleado = new PrincipalEmpleado();
            principalEmpleado.setVisible(true);
            this.dispose();
        } catch (ConstraintViolationException e) {
            mostrarErrorValidaciones(e);
        } catch (IllegalArgumentException e) {
            mostrarDialogo(e.getMessage(),
                    "ERROR DE AUTENTICACIÓN",
                    JOptionPane.ERROR_MESSAGE);
        } catch (SQLException e) {
            mostrarDialogo(e.getMessage(),
                    "ERROR DE CONEXIÓN",
                    JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            mostrarDialogo("Error inesperado: " + e.getMessage(),
                    "ERROR",
                    JOptionPane.ERROR_MESSAGE);
        } finally {
            pwdfPassword.setText("");
            txtfEmail.requestFocus();
        }
    }
    
    private void mostrarDialogo(String mensaje, String titulo, int tipoMensaje) {
        JOptionPane.showMessageDialog(
                this,
                mensaje,
                titulo,
                tipoMensaje);
    }
    
    private void mostrarErrorValidaciones(ConstraintViolationException e) {
        StringBuilder mensajeError = new StringBuilder("Errores de validación:\n");
        e.getConstraintViolations().forEach(violation ->
            mensajeError.append("- ").append(violation.getMessage()).append("\n")
        );
        mostrarDialogo(mensajeError.toString(),
                "DATOS INVÁLIDOS",
                JOptionPane.ERROR_MESSAGE);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JComboBox<String> cbxRol;
    private javax.swing.JPanel header;
    private javax.swing.JLabel lblBienvenida;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblRol;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPasswordField pwdfPassword;
    private javax.swing.JSeparator separado1;
    private javax.swing.JSeparator separador2;
    private javax.swing.JTextField txtfEmail;
    // End of variables declaration//GEN-END:variables
}
